CREATE DATABASE airbnb;

USE airbnb;

CREATE TABLE reviews (
  id INTEGER NOT NULL AUTO_INCREMENT,
  experience_id INTEGER NOT NULL,
  username VARCHAR(20) NOT NULL,
  avatar VARCHAR(150) NOT NULL,
  date DATE NOT NULL,
  stars INTEGER NOT NULL,
  review VARCHAR(400) NOT NULL,
  PRIMARY KEY(id)
);


